CREATE TABLE "order"(
    id       INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    status VARCHAR(20) NOT NULL UNIQUE,
    user_id  INT NOT NULL,
    number    VARCHAR(200) NOT NULL UNIQUE,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now() 
);