CREATE TABLE IF NOT EXISTS "balance"(
    id          INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY ,
    balance     DOUBLE PRECISION NOT NULL,
    user_id     INT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now() 
);